apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: microstore
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      name: mysql
  clusterIP: None   # servicio headless
  selector:
    app: mysql